server:
  port: 8082

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server.webflux: # Add the 'mvc' node here
        routes:
          # --- Program Management Service ---
          - id: program-mgmt-route
            uri: lb://PROGRAMMANAGMENTAPPLICATION
            predicates:
              - Path=/api/programs/**, /api/resources/**, /api/reports/**, /api/incidents/**

          - id: audit-route
            uri: lb://AUDITCOMPLIANCEMANAGEMENT
            predicates:
              - Path=/api/audits/**,/api/compliance-records/**
          - id: audit-log-route
            uri: lb://USERCITIZENMANAGEMENT
            predicates:
              - Path=/api/logs/**
          - id: user-mgmt-route
            uri: lb://USERCITIZENMANAGEMENT
            predicates:
              - Path=/api/users/**
          - id: citizen-mgmt-route
            uri: lb://USERCITIZENMANAGEMENT
            predicates:
              - Path=/api/citizens/**

          # --- User & Citizen Management Module ---




          - id: relief-item-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/ReliefItems/**

          - id: distribution-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/Distributions/**
          - id: document-route
            uri: lb://USERCITIZENMANAGEMENT # Replace with your actual Eureka Service ID
            predicates:
              - Path=/api/documents/**

          - id: reports-route
            uri: lb://USERCITIZENMANAGEMENT # Replace with your actual Eureka Service ID
            predicates:
              - Path=/api/reports/**
          - id: shelter-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/api/shelters/**
            # This removes the first two parts (/api/audits)
            # so the Audit service only sees "/all"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework: TRACE
#    org.springframework.http.server: TRACE