server:
  port: 8082

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc: # Add the 'mvc' node here
        routes:
          - id: Recoveryprogram-route
            uri: lb://PROGRAMMANAGMENTAPPLICATION
            predicates:
              - Path=/api/programs/**
          - id: Resource-route
            uri: lb://PROGRAMMANAGMENTAPPLICATION
            predicates:
              - Path=/api/resources/**
          - id: audit-route
            uri: lb://AUDITCOMPLIANCEMANAGEMENT
            predicates:
                - Path=/api/audits/**
          - id: compliance-route
            uri: lb://AUDITCOMPLIANCEMANAGEMENT
            predicates:
            - Path=/api/audits/**

          - id: relief-item-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/ReliefItems/**

          - id: distribution-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/Distributions/**

          - id: shelter-route
            uri: lb://RELIEFMANAGEMENTAPPLICACTION
            predicates:
              - Path=/api/Shelters/**
            # This removes the first two parts (/api/audits)
            # so the Audit service only sees "/all"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: TRACE
    org.springframework.http.server: TRACE